
spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    username: admin
    password: 
    url: jdbc:h2:mem:albumapp
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"