spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/albumapp-qa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  config:
    activate:
      on-profile: qa
