package com.sshpro.album.repository;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;

import com.sshpro.album.entity.Album;
import com.sshpro.album.util.TestData;

@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
class AlbumRepositoryTest {
    @Autowired
    private AlbumRepository albumRepository;

    @Autowired
    private TestEntityManager testEntityManager;

    private Long albumId;

    @BeforeEach
    void setUp() {
        // Never create object with primary key if it is autogenerated
        Album album = testEntityManager.persist(TestData.getAlbum());
        albumId = album.getId();
    }

    @Test
    public void whenFindById_thenReturnAlbum() {
        Album album = albumRepository.findById(albumId).get();
        assertEquals(album.getTitle(), "Title");
    }
}