server:
    port: 9191
    
spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: ALBUM-SERVICE
          uri: lb://ALBUM-SERVICE
          predicates:
            - Path=/albums/**
  config:
    import: configserver:http://localhost:9296