server:
    port: 9001
    
spring:
  application:
    name: USER-SERVICE
  h2:
    console:
      enabled: 'true'
  datasource:
    username: admin
    password: 
    url: jdbc:h2:mem:userapp
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    register-with-eureka: 'true'
    fetch-registry: 'true'
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost