server:
    port: 9001
    
spring:
  application:
    name: USER-SERVICE
  h2:
    console:
      enabled: 'true'
  datasource:
    username: admin
    password: 
    url: jdbc:h2:mem:userapp
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import: configserver:http://localhost:9296